services:
  postgres:
    image:
      postgres:14-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
